#!/bin/bash
# echo "$(grep -v '^#' ~/.local/share/chezmoi/dot_local/sync/snippets | dmenu -i -l 20 | cut -d' ' -f1)" | xclip -selection clipboard 
echo "$(grep -v '^#' ~/.local/sync/files/snippets | fuzzel -d | cut -d' ' -f1)" | wl-copy
